services:
  front:
    build: ./front
    container_name: noe-front
    restart: unless-stopped
    ports:
      - "3001:3000"

  db:
    image: pgvector/pgvector:pg17
    container_name: noe-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "3000:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro

volumes:
  db_data:
