services:
  front:
    build: ./front
    container_name: noe-front
    restart: unless-stopped
    ports:
      - "3001:3000"

  qdrant:
    image: qdrant/qdrant:v1.15.4
    container_name: noe-qdrant
    restart: unless-stopped
    environment:
      QDRANT__SERVICE__API_KEY: ${QDRANT_API_KEY}
    ports:
      - "3000:6333"
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
