// Real-Qdrant integration test. Requires a running Qdrant; never substitutes a mock.
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { once } from 'node:events';
import { loadConfig } from '../src/config.mjs';
import { createServer } from '../src/server.mjs';
import { QdrantClient } from '../src/db/qdrant.mjs';
import { ProfilesRepository } from '../src/db/profiles.mjs';

const config = loadConfig();
const collection = `kmu_test_${randomUUID().replaceAll('-', '')}`;
const client = new QdrantClient(config.qdrant);
const app = createServer({ config, repository: new ProfilesRepository(client, collection) });
let created = false;
try {
  // Fail fast before creating any fixture if the real server is unreachable.
  await client.request('GET', '/collections');
  app.listen(0, '127.0.0.1'); await once(app, 'listening');
  const base = `http://127.0.0.1:${app.address().port}/api/db/profiles`;
  const profile = { studentType: '학부', college: '테스트 단과대학', major: '테스트 전공', grade: 2, interests: ['테스트'], customInterests: [], keywords: [] };
  created = true;
  const response = await fetch(base, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(profile) });
  assert.equal(response.status, 201, JSON.stringify(await response.clone().json()));
  const saved = await response.json();
  const read = await (await fetch(`${base}/${saved.id}`)).json();
  assert.deepEqual(read, saved);
  const point = await client.point(collection, saved.id);
  assert.deepEqual(point.payload.profile, profile);
  // A fresh repository instance confirms retrieval does not rely on process memory.
  const fresh = new ProfilesRepository(new QdrantClient(config.qdrant), collection);
  assert.deepEqual((await fresh.get(saved.id)).profile, profile);
  const update = await fetch(`${base}/${saved.id}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...profile, grade: 3 }) });
  assert.equal(update.status, 200);
  assert.equal((await client.point(collection, saved.id)).payload.profile.grade, 3);
  console.log('PASS: 실제 Qdrant 저장/조회/수정 및 새 클라이언트 재조회');
} catch (error) {
  console.error('FAIL: 실제 Qdrant 통합 검증 실패. Docker 또는 QDRANT_URL 설정을 확인하세요.', error.message);
  process.exitCode = 1;
} finally {
  app.closeAllConnections(); if (app.listening) await new Promise(resolve => app.close(resolve));
  // Only remove the unique test collection generated by this invocation.
  if (created && /^kmu_test_[a-f0-9]{32}$/.test(collection)) {
    try { await client.request('DELETE', client.collectionPath(collection)); console.log('테스트 전용 컬렉션 정리 완료'); }
    catch { console.error(`테스트 컬렉션 정리 실패: ${collection}`); process.exitCode = 1; }
  }
}
